-- util global is not available during settings stage and must be imported.
local util = require("util")

data:extend({
	{
		type = "string-setting",
		name = "reskins-framework-tier-mapping",
		setting_type = "startup",
		order = "b",
		default_value = "progression-map",
		allowed_values = { "progression-map", "traditional-map" },
	},
	{
		type = "string-setting",
		name = "reskins-framework-tier-label-style",
		setting_type = "startup",
		order = "bb",
		default_value = "rounded-rectangle",
		allowed_values = {
			"chevron",
			"dots",
			"half-circle",
			"rectangle",
			"rounded-half-circle",
			"rounded-rectangle",
			"teardrop",
		},
	},
	{
		type = "bool-setting",
		name = "reskins-framework-show-tier-labels",
		setting_type = "startup",
		order = "c",
		default_value = true,
	},
	{
		type = "bool-setting",
		name = "reskins-framework-show-tier-labels-on-pipes",
		setting_type = "startup",
		order = "cc",
		default_value = true,
	},
	{
		type = "bool-setting",
		name = "reskins-framework-use-custom-tier-colors",
		setting_type = "startup",
		order = "y",
		default_value = false,
	},
	{
		type = "color-setting",
		name = "reskins-framework-custom-colors-tier-0",
		setting_type = "startup",
		order = "yy",
		default_value = util.color("#808080"),
	},
	{
		type = "color-setting",
		name = "reskins-framework-custom-colors-tier-1",
		setting_type = "startup",
		order = "yy",
		default_value = util.color("#FFB726"),
	},
	{
		type = "color-setting",
		name = "reskins-framework-custom-colors-tier-2",
		setting_type = "startup",
		order = "yy",
		default_value = util.color("#F22318"),
	},
	{
		type = "color-setting",
		name = "reskins-framework-custom-colors-tier-3",
		setting_type = "startup",
		order = "yy",
		default_value = util.color("#33B4FF"),
	},
	{
		type = "color-setting",
		name = "reskins-framework-custom-colors-tier-4",
		setting_type = "startup",
		order = "yy",
		default_value = util.color("#B459FF"),
	},
	{
		type = "color-setting",
		name = "reskins-framework-custom-colors-tier-5",
		setting_type = "startup",
		order = "yy",
		default_value = util.color("#2EE55C"),
	},
	{
		type = "color-setting",
		name = "reskins-framework-custom-colors-tier-6",
		setting_type = "startup",
		order = "yy",
		default_value = util.color("#FF8533"),
	},

	-- Hidden, overridable settings that control the "default" color tiers.
	{
		type = "color-setting",
		name = "reskins-framework-default-colors-tier-0",
		setting_type = "startup",
		order = "yy",
		default_value = util.color("#808080"),
		hidden = true,
	},
	{
		type = "color-setting",
		name = "reskins-framework-default-colors-tier-1",
		setting_type = "startup",
		order = "yy",
		default_value = util.color("#ffb726"),
		hidden = true,
	},
	{
		type = "color-setting",
		name = "reskins-framework-default-colors-tier-2",
		setting_type = "startup",
		order = "yy",
		default_value = util.color("#f22318"),
		hidden = true,
	},
	{
		type = "color-setting",
		name = "reskins-framework-default-colors-tier-3",
		setting_type = "startup",
		order = "yy",
		default_value = util.color("#33b4ff"),
		hidden = true,
	},
	{
		type = "color-setting",
		name = "reskins-framework-default-colors-tier-4",
		setting_type = "startup",
		order = "yy",
		default_value = util.color("#b459ff"),
		hidden = true,
	},
	{
		type = "color-setting",
		name = "reskins-framework-default-colors-tier-5",
		setting_type = "startup",
		order = "yy",
		default_value = util.color("#2ee55c"),
		hidden = true,
	},
	{
		type = "color-setting",
		name = "reskins-framework-default-colors-tier-6",
		setting_type = "startup",
		order = "yy",
		default_value = util.color("#ff8533"),
		hidden = true,
	},
})
